package main

import (
	"go-by-example/example"
)

func main() {
	example.HelloWorld()
	example.Values()
	example.Variables()
	example.Constants()
	example.For()
	example.IfElse()
	example.Switch()
	example.Arrays()
	example.Maps()
	example.Range()
	example.Functions()
	example.MultipleReturnValues()
	example.VariadicFunction()
	example.Closures()
	example.Recursion()
	example.Pointers()
	example.Structs()
	example.Methods()
	example.Interfaces()
	example.Errors()
	example.Goroutine()
	example.Channels()
	example.ChannelSync()
	example.Select()
	example.Timeouts()
	example.NonBlockChannel()
	example.ClosingChannel()
	example.RangeOverChannel()
	example.Timer()
	example.Ticker()
	example.WorkPool()
	example.WaitGroup()
	example.RateLimiting()
	example.AtomicCounter()
	example.Mutexe()
	example.StatefulGoroutine()
	example.Sorting()
	example.SortByFunc()
	// example.Panic()
	// example.Defer()
	example.CollectionFunc()
	example.StringFunc()
}
